add check for changes.txt
- error out if no changes.txt is found

diff --git a/force_package_update b/force_package_update
--- a/force_package_update
+++ b/force_package_update
@@ -1,5 +1,10 @@
 unset ERROR
 
+if [ ! -f /boot/changes.txt ]; then
+  echo "Error: Force Plugin Updates can't start! Can't find file /boot/changes.txt"
+  exit 1
+fi
+
 echo "Force Plugin Updates script version: 2023.08.31 by ich777"
 echo
 echo "Please don't close this window until it says finished!"
